apiVersion: v1
kind: ConfigMap
metadata:
  name: book-management-api-config
data:
  # Database configuration
  DATABASE_URL: "postgresql+asyncpg://postgres:postgres@postgres-service:5432/bookdb"
  
  # Application settings
  LOG_LEVEL: "INFO"
  ENVIRONMENT: "production"
  
  # LLM Service configuration
  LLM_API_KEY: ""  # Should be replaced with a Secret in production
  LLM_MODEL_NAME: "gpt-3.5-turbo"
  LLM_TIMEOUT_SECONDS: "30"
  
  # Ollama configuration
  OLLAMA_API_URL: "http://ollama-service:11434"
  OLLAMA_MODEL: "llama2"
  OLLAMA_MAX_TOKENS: "2048"
  OLLAMA_TEMPERATURE: "0.7"
  OLLAMA_TOP_P: "0.9"
  OLLAMA_TIMEOUT: "120"
