apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-management-api
  labels:
    app: book-management-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-management-api
  template:
    metadata:
      labels:
        app: book-management-api
    spec:
      containers:
      - name: book-management-api
        image: book-management-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
        envFrom:
        - configMapRef:
            name: book-management-api-config
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
